# Generated by Django 4.2.3 on 2023-08-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_goodscategory_options_alter_goods_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={},
        ),
        migrations.AlterModelTable(
            name='goods',
            table=None,
        ),
        migrations.AlterModelTable(
            name='goodscategory',
            table=None,
        ),
    ]
